### ISSUE TITLE
[Bug?] Error when use command

### ISSUE THREAD

**Issue by Yurinann** [WiIIiam278/HuskHomes2#131]
```
[11:30:31 INFO]: TangXuanzi issued server command: /home
[11:30:36 WARN]: [HuskHomes] Plugin HuskHomes v2.11.2 generated an exception while executing task 37514
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getPlayerExact(CraftServer.java:554) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.Bukkit.getPlayerExact(Bukkit.java:440) ~[forge:?]
        at me.william278.huskhomes2.teleport.TeleportManager.setPlayerDestinationFromTargetPlayer(TeleportManager.java:269) ~[?:?]
        at me.william278.huskhomes2.teleport.TeleportManager.teleportPlayer(TeleportManager.java:42) ~[?:?]
        at me.william278.huskhomes2.teleport.TimedTeleport$1.lambda$run$0(TimedTeleport.java:114) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:98) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Server: Mohist 1.16.5

**Comment by WiIIiam278** [comment]
Sorry, Mohist is not supported
