### ISSUE TITLE
SQLite DB can get busy preventing operations from completing

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#148]
plugin will be slow to respond on any tp. I don't know if it has something to do with my device, I've tried using a solid state drive as well
Often gets stuck for a few seconds, Sometimes there are also SQL error[even if the load is not high]. I use SQLite
I noticed that on any operation a db-journal file is generated, This file seems to be stuck for a while[About 1 to 2 s]
These are the errors I found:

Occurs when a teleportation point is created
```
[ERROR]: [HuskHomes] An SQL exception occurred!
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1012) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.execute(DB.java:863) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.executeUpdate(DB.java:904) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98) ~[patched_1.17.1.jar:git-Purpur-1428]
        at me.william278.huskhomes2.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.addTeleportationPoint(DataManager.java:666) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.addHome(DataManager.java:828) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.addHome(DataManager.java:839) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.teleport.SettingHandler.lambda$setHome$0(SettingHandler.java:47) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
.
Occurs in some teleportation
```
[ERROR]: [HuskHomes] An SQL exception occurred teleporting a player.
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1012) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.execute(DB.java:863) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.executeUpdate(DB.java:904) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98) ~[patched_1.17.1.jar:git-Purpur-1428]
        at me.william278.huskhomes2.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.deleteTeleportationPoint(DataManager.java:752) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.deletePlayerLastPosition(DataManager.java:759) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.setPlayerLastPosition(DataManager.java:705) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.teleport.TeleportManager.teleportPlayer(TeleportManager.java:53) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.teleport.TeleportManager.queueTimedTeleport(TeleportManager.java:131) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.commands.PublicHomeCommand.lambda$queueHomeTeleport$1(PublicHomeCommand.java:59) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]


[ERROR]: [HuskHomes] An exception occurred teleporting to a public home.
[WARN]: [HuskHomes] Plugin HuskHomes v2.11.2 generated an exception while executing task 311
java.lang.IllegalArgumentException: Could not return a teleportationPoint from the locations data table at (ID#60)
        at me.william278.huskhomes2.data.DataManager.getTeleportationPoint(DataManager.java:619) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.getPlayerDestination(DataManager.java:627) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.teleport.TeleportManager.lambda$teleportPlayer$5(TeleportManager.java:76) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]


[WARN]: [HuskHomes] Plugin HuskHomes v2.11.2 generated an exception while executing task 340
java.lang.IllegalArgumentException: Could not return a teleportationPoint from the locations data table at (ID#0)
        at me.william278.huskhomes2.data.DataManager.getTeleportationPoint(DataManager.java:619) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.getPlayerDestination(DataManager.java:627) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.teleport.TeleportManager.lambda$teleportPlayer$5(TeleportManager.java:76) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
.
and a just discovered
```
[ERROR]: [HuskHomes] An SQL error handling a joining player
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1012) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.execute(DB.java:863) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.core.DB.executeUpdate(DB.java:904) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98) ~[patched_1.17.1.jar:git-Purpur-1428]
        at me.william278.huskhomes2.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.addPlayer(DataManager.java:352) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.addPlayer(DataManager.java:341) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.createPlayer(DataManager.java:861) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.listeners.PlayerListener.lambda$onPlayerJoin$1(PlayerListener.java:52) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WiIIiam278** [comment]
Is this occurring on a busy server (how many players online)?

**Comment by From-pErfo** [comment]
There are very few players, you can get these errors as long as the commands are faster

**Comment by WiIIiam278** [comment]
Probably caused by me migrating to Hikari, need to revert back to using persistent connection for SQLite but that requires a rewrite unfortunately

**Comment by From-pErfo** [comment]
I always thought it had something to do with the teleportation part, like minecraft's tp command[it executes fast]
Because the plugin has no delay in outputting the home list

**Comment by From-pErfo** [comment]
Can it be resolved as soon as possible? As the number of players increases, its impact becomes very large, but since the data is stored here, I can't find an alternative...

**Comment by WiIIiam278** [comment]
Patience.

**Comment by From-pErfo** [comment]
I added a better SSD to the server, and that seemed to solve the problem

**Comment by WiIIiam278** [comment]
> I added a better SSD to the server, and that seemed to solve the problem

That's good to hear - though this issue will still occur on slower machines so I'm reopening

**Comment by From-pErfo** [comment]
When I updated the server to 1.19, the problem reappeared and was worse than before. When the player uses /home to view all teleportation points, if the number of teleportation points is small, the server will freeze for a few seconds and then resume, if the number of teleportation points exceeds 20, the server will crash directly. 
server: `paper-1.19-81`
plugin: `2.11.2`
using sqlite.

**Comment by From-pErfo** [comment]
> When I updated the server to 1.19, the problem reappeared and was worse than before. When the player uses /home to view all teleportation points, if the number of teleportation points is small, the server will freeze for a few seconds and then resume, if the number of teleportation points exceeds 20, the server will crash directly. The same problem occurs even if I empty the database and recreate several teleports. (It also works for /warp) server: `paper-1.19-81` plugin: `2.11.2` using sqlite.


I switched to MariaDB and the problem persists

**Comment by WiIIiam278** [comment]
v2.0 will address this issue with new DB handling, so please be patient.
