### ISSUE TITLE
/tpaccept with no arguments when the player has no requests throws exception

### ISSUE THREAD

**Issue by gepao233** [WiIIiam278/HuskHomes2#228]
Typing '/tpaccept' will cause an error when the player has no extra teleport requests.
HuskHomes Versions:3.0.3
Server Versions:Paper-1.19.1

Log:
[15:44:01] [Server thread/INFO]: harveyminer issued server command: /tpaccept
[15:44:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tpaccept' in plugin HuskHomes v3.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59) ~[paper-1.19.1.jar:git-Paper-111]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:248) ~[?:?]
	at net.william278.huskhomes.request.RequestManager.getLastTeleportRequest(RequestManager.java:93) ~[HuskHomes-3.0.3.jar:?]
	at net.william278.huskhomes.request.RequestManager.respondToTeleportRequest(RequestManager.java:245) ~[HuskHomes-3.0.3.jar:?]
	at net.william278.huskhomes.command.TpRespondCommand.onExecute(TpRespondCommand.java:40) ~[HuskHomes-3.0.3.jar:?]
	at net.william278.huskhomes.command.BukkitCommand.onCommand(BukkitCommand.java:54) ~[] HuskHomes-3.0.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by WiIIiam278** [comment]
Oversight because the buttons use the tpaccept/decline with the username arg
