### ISSUE TITLE
IllegalStateException thrown when teleporting to a world that is no longer available on server

### ISSUE THREAD

**Issue by ReferTV** [WiIIiam278/HuskHomes2#24]
[13:39:26] [Server thread/ERROR]: [HuskHomes] Task #83 for HuskHomes v2.2 generated an exception
[13:39:26] [Server thread/ERROR]: [HuskHomes] Suspected Plugins: 
[13:39:26] [Server thread/ERROR]: [HuskHomes] 	HuskHomes{enabled,ver=2.2,path=plugins/HuskHomes-2.2.jar}
[13:39:26] [Server thread/ERROR]: [HuskHomes] Exception details below: 
java.lang.IllegalStateException: The world "the_end" could not be found on the server; could not return location
	at me.william278.huskhomes2.teleport.points.TeleportationPoint.getLocation(TeleportationPoint.java:78) ~[?:?]
	at me.william278.huskhomes2.teleport.TeleportManager.teleportPlayer(TeleportManager.java:38) ~[?:?]
	at me.william278.huskhomes2.teleport.TeleportManager.teleportPlayer(TeleportManager.java:30) ~[?:?]
	at me.william278.huskhomes2.teleport.TeleportRequestHandler.lambda$startExpiredChecker$0(TeleportRequestHandler.java:197) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1393) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:402) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1302) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1023) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by WiIIiam278** [comment]
Should throw an error to the user rather than in console, and possibly prompt them to delete the home.
