### ISSUE TITLE
mulitpaper BUG

### ISSUE THREAD

**Issue by dongzh1** [WiIIiam278/HuskHomes2#253]
[22:01:43 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:27}] to localhost:27017
[22:01:48 ERROR]: [HuskHomes] Failed to fetch server name from the proxy (attempts: 5) - Is your proxy server online?
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2874) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:01:50 ERROR]: Could not pass event PlayerTeleportEvent to HuskHomes v3.1
net.william278.huskhomes.HuskHomesException: Attempted to access server when it was not initialized
        at net.william278.huskhomes.BukkitHuskHomes.getPluginServer(BukkitHuskHomes.java:462) ~[HuskHomes-3.1.jar:?]
        at net.william278.huskhomes.listener.BukkitEventListener.lambda$onPlayerTeleport$0(BukkitEventListener.java:60) ~[HuskHomes-3.1.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.william278.huskhomes.listener.BukkitEventListener.onPlayerTeleport(BukkitEventListener.java:59) ~[HuskHomes-3.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:MultiPaper-1.19.2-37]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1344) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1255) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1250) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:543) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at dev.lone.itemsadder.main.hs.ac(SourceFile:151) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.main.hp.a(SourceFile:180) ~[ItemsAdder_3.2.3-r10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor670.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:MultiPaper-1.19.2-37]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2132) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

I use mulit-master and mulitpaper (latest,https://multipaper.io/download.html) 
Player1 join server1
Player2 join server2
teleport function error

**Comment by WiIIiam278** [comment]
Not compatible with MultiPaper. This is a paper or spigot plugin that supports cross-server functionality in a traditional proxy-style setup.
