### ISSUE TITLE
BUG, Error when typing /delwarp without args

### ISSUE THREAD

**Issue by Miriam0** [WiIIiam278/HuskHomes2#264]
![image](https://user-images.githubusercontent.com/46651542/203336856-a8721cf7-c835-4ac4-974d-f1c9435ce453.png)
[17:16:11 ERROR]: Unhandled exception executing command 'delwarp' in plugin HuskHomes v3.1
org.bukkit.command.CommandException: Unhandled exception executing command 'delwarp' in plugin HuskHomes v3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:717) ~[EssentialsX-2.20.0-dev+11-b150542.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:703) ~[EssentialsX-2.20.0-dev+11-b150542.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:989) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[multipaper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2343) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at net.william278.huskhomes.command.DelWarpCommand.onExecute(DelWarpCommand.java:25) ~[HuskHomes-3.1.jar:?]
        at net.william278.huskhomes.command.BukkitCommand.onCommand(BukkitCommand.java:55) ~[HuskHomes-3.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 26 more
>

**Comment by Miriam0** [comment]
![image](https://user-images.githubusercontent.com/46651542/204044978-add8c46e-9c17-466a-a270-a361fa499a1b.png)
also bug i can create any count of homes when i don't have permission for that

**Comment by Miriam0** [comment]
![image](https://user-images.githubusercontent.com/46651542/204045092-bd06d5e7-679d-4a75-b042-c640b9ae101f.png)
lp editor:
![image](https://user-images.githubusercontent.com/46651542/204045116-6bed43cd-85bd-4185-9e05-6a425d4b91f6.png)
