### ISSUE TITLE
"Message dispatch after 5 seconds" error - Cross-server operations stop working after a random period of time

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskHomes2#275]
Network messages start to fail and instead time out for some users after a period of time. Particularly prevalent with users running HuskSync, seemingly.

I'm not entirely sure what causes this, to be honest. Messages seem to just not get sent in certain cases -- and this _doesn't seem_ to be specific to Plugin Messages or Redis, seems to happen to both. Best guess is something to do with Java's future Multi-threading not liking the current setup. This issue might require a rewrite of some of the networking logic.

**Comment by sfclog** [comment]
Nice

**Comment by WiIIiam278** [comment]
> Nice

If you're experiencing this issue, by all means please feel free to provide relevant stack traces, suggestions or other meaningful contributions ;-)

**Comment by CodeZhangBorui** [comment]
This is a relevant stack traces on my Paper-1.17.1 server, but I don't know if this information can help you.

```
[19:46:45] [Thread-12/INFO]: [HuskHomes] Migrating SQLite database, please wait... This may take a while!
[19:46:45] [Thread-12/INFO]: [HuskHomes] Successfully performed automatic upgrade.
[19:46:45] [Thread-13/ERROR]: [HuskHomes] An exception occurred running script on the SQLite database
java.sql.BatchUpdateException: batch entry 2: [SQLITE_ERROR] SQL error or missing database (no such table: huskhomes_location_data)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:198) ~[patched_1.17.1.jar:git-Paper-408]
	at net.william278.huskhomes.database.SqLiteDatabase.lambda$runScript$1(SqLiteDatabase.java:126) ~[HuskHomes-3.2.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:46:45] [Thread-13/ERROR]: [HuskHomes] Migration of SQLite database failed! Perhaps the target tables was not clean?
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.sql.BatchUpdateException: batch entry 2: [SQLITE_ERROR] SQL error or missing database (no such table: huskhomes_location_data)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.sql.BatchUpdateException: batch entry 2: [SQLITE_ERROR] SQL error or missing database (no such table: huskhomes_location_data)
	at net.william278.huskhomes.database.SqLiteDatabase.lambda$runScript$1(SqLiteDatabase.java:131) ~[HuskHomes-3.2.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 1 more
Caused by: java.sql.BatchUpdateException: batch entry 2: [SQLITE_ERROR] SQL error or missing database (no such table: huskhomes_location_data)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:198) ~[patched_1.17.1.jar:git-Paper-408]
	at net.william278.huskhomes.database.SqLiteDatabase.lambda$runScript$1(SqLiteDatabase.java:126) ~[HuskHomes-3.2.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 1 more
```

The same error happened twice in one day, and it will prevent server from restarting.

**Comment by WiIIiam278** [comment]
This isn't related to this issue. It seems like migration wasn't carried out properly for you when you upgraded from 2.x to 3.x

**Comment by CodeZhangBorui** [comment]
> This isn't related to this issue. It seems like migration wasn't carried out properly for you when you upgraded from 2.x to 3.x

Thank you. I will try to solve this problem myself.

**Comment by WiIIiam278** [comment]
A user mentioned setting their cluster ID back to ‘’ (blank) on every server helped

**Comment by LuluxClient** [comment]
Same issue and my cluster ID is indeed blank: cluster_id: '' 

Error:
```
[13:45:58 WARN]: [HuskHomes] Message dispatch after 5 seconds
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2874) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```
        Yes there is only that

**Comment by WiIIiam278** [comment]
This isn't related to the subnetwork clustering system. 

It's caused by thread pool exhaustion causing issues when joining concurrent futures (used for tracking cross server message processing and DB querying), exasperated by low-core allocations on a lot of MC server instances.

In essence, it requires some fairly meaty rewriting of the cross-server communication system, which is tied up in a huge number of other areas in the plugin code. I'm working on it, though, little by little. Thanks for your patience.
