### ISSUE TITLE
Error happed when upgrading from v2 to v3

### ISSUE THREAD

**Issue by MagmaBlock** [WiIIiam278/HuskHomes2#281]
Following the docs https://william278.net/docs/huskhomes/upgrading-from-v2, when the v3 plugin starts for the first time, some mysql error happened

use data of v2.11.2 update to v3.x
I try to upgrade to 3.0, 3.0.4, 3.1 and 3.2.1 with the same 2.11.2 data, but all failed
the log are here:
```
[02:59:02] [Server thread/INFO]: [HuskHomes] Enabling HuskHomes v3.0
[02:59:02] [Server thread/INFO]: [HuskHomes] Loading plugin configuration settings & locales...
[02:59:02] [Server thread/WARN]: [HuskHomes] Upgrading critical HuskHomes v2.x settings to v3.x.
[02:59:02] [Server thread/INFO]: [HuskHomes] Successfully loaded plugin configuration settings & locales
[02:59:02] [Server thread/INFO]: [HuskHomes] Attempting to establish connection to the database...
[02:59:02] [Server thread/INFO]: [net.william278.huskhomes.libraries.hikari.HikariDataSource] HuskHomesHikariPool - Starting...
[02:59:02] [Server thread/INFO]: [net.william278.huskhomes.libraries.hikari.pool.HikariPool] HuskHomesHikariPool - Added connection com.mysql.cj.jdbc.ConnectionImpl@1df75ddc
[02:59:02] [Server thread/INFO]: [net.william278.huskhomes.libraries.hikari.HikariDataSource] HuskHomesHikariPool - Start completed.
[02:59:21] [Server thread/INFO]: [HuskHomes] Successfully established a connection to the database

// an error here, it seems that the old data has not been converted
[02:59:21] [ForkJoinPool.commonPool-worker-1/ERROR]: [HuskHomes] Failed to query the database for public home data 

[02:59:21] [Server thread/INFO]: [Plan] Registered extension: HuskHomes
[02:59:21] [Server thread/INFO]: [HuskHomes] Registered 1 plugin hooks: Plan
[02:59:21] [Server thread/INFO]: [HuskHomes] Registering events...
[02:59:21] [Server thread/INFO]: [HuskHomes] Successfully registered events listener
[02:59:21] [Server thread/INFO]: [HuskHomes] Registering permissions & commands...
[02:59:21] [Server thread/INFO]: [HuskHomes] Successfully registered permissions & commands.
[02:59:21] [Server thread/INFO]: [HuskHomes] Checking for updates...
[02:59:21] [Server thread/INFO]: [HuskHomes] Performing automatic upgrade...
[02:59:21] [ForkJoinPool.commonPool-worker-7/INFO]: [HuskHomes] Migrating MySQL database, please wait... This may take a while!
[02:59:21] [Server thread/INFO]: [HuskHomes] Successfully enabled HuskHomes v3.0
[02:59:21] [ForkJoinPool.commonPool-worker-7/INFO]: [HuskHomes] Successfully performed automatic upgrade.
[02:59:22] [ForkJoinPool.commonPool-worker-1/WARN]: [HuskHomes] An update is available for HuskHomes, v3.2.1 (Currently running v3.0)


// after a while, the 'unknow column uuid' called
[02:59:41] [ForkJoinPool.commonPool-worker-3/ERROR]: [HuskHomes] An error occurred running a script on the MySQL database: 
java.sql.BatchUpdateException: Unknown column 'uuid' in 'field list'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:897) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at net.william278.huskhomes.libraries.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.libraries.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.database.MySqlDatabase.lambda$runScript$1(MySqlDatabase.java:114) ~[HuskHomes-3.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'uuid' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1340) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:863) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	... 11 more
[02:59:41] [ForkJoinPool.commonPool-worker-3/ERROR]: [HuskHomes] Migration of MySQL database failed! Perhaps the target tables was not clean?
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.sql.BatchUpdateException: Unknown column 'uuid' in 'field list'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.RuntimeException: java.sql.BatchUpdateException: Unknown column 'uuid' in 'field list'
	at net.william278.huskhomes.database.MySqlDatabase.lambda$runScript$1(MySqlDatabase.java:118) ~[HuskHomes-3.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
Caused by: java.sql.BatchUpdateException: Unknown column 'uuid' in 'field list'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:897) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at net.william278.huskhomes.libraries.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.libraries.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.database.MySqlDatabase.lambda$runScript$1(MySqlDatabase.java:114) ~[HuskHomes-3.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'uuid' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1340) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:863) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at net.william278.huskhomes.libraries.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.libraries.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) ~[HuskHomes-3.0.jar:?]
	at net.william278.huskhomes.database.MySqlDatabase.lambda$runScript$1(MySqlDatabase.java:114) ~[HuskHomes-3.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
```

Is this because my old data has a wrong table structure? but v2 works well...
here are table structure in v2:

![image](https://user-images.githubusercontent.com/61128045/205724980-08562dee-fa41-4104-be8e-23a0bb8d6eba.png)
![image](https://user-images.githubusercontent.com/61128045/205725067-b2b6e6d4-b62e-4eff-9e3b-409feb15f872.png)
![image](https://user-images.githubusercontent.com/61128045/205725149-821ed09b-5b1e-48d1-98ff-79255b75d43c.png)
![image](https://user-images.githubusercontent.com/61128045/205725212-0bd74db5-76cb-4420-b9c5-a44087ed3572.png)

**Comment by WiIIiam278** [comment]
Are you sure you didn't accidentally delete the HuskHomes v2.x config on startup? What's happening here indicates you didn't quite follow the instructions correctly. From the docs:
```
In your plugins/HuskHomes/ folder, delete the messages.yml file to let it regenerate.
```
You must not delete the existing config, or create a new one and adjust the tables -- HuskHomes will automatically do this and migrate your config over for you.

In any case, to fix this:
1. In your config.yml file, ensure your MySQL credentials are set correctly and that the _table names in the config point to new tables_ that have not been created yet -- thus, allowing HuskHomes to generate new tables.
2. Restart all servers
3. One one server, type `huskhomes migrate legacy` _through console_ and follow the on-screen instructions to ensure the names of the tables in the migrator are the old tables.
4. Run the migrator.

**Comment by MagmaBlock** [comment]
It works! Thank you very very much
