### ISSUE TITLE
viaversion bugged with huskhomes

### ISSUE THREAD

**Issue by masterblaster221** [WiIIiam278/HuskHomes2#353]
I am are unable to teleport cross-server with both plugins active, 2 of my servers on 1.12.2  teleportation works yet not cross-server, and my 3 paper servers on 1.19.2 don't work either. I know the MySQL is working because I can send teleportation requests the timer counts down and nothing. also, it says Mysql initializes and I get this error.

**Comment by masterblaster221** [comment]
endi0 issued server command: /huskhomes:back
[09:50:10 ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1b6cbcb8, value=Item{identifier=788, amount=2, data=0, tag=null}}
[09:50:10 ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@47c3978e, value=0}
Metadata{id=1, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@398f7f09, value=300}
Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7a7bb28, value=null}
Metadata{id=3, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@6f7b8129, value=false}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@6f7b8129, value=false}
Metadata{id=5, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@6f7b8129, value=false}
Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1b6cbcb8, value=Item{identifier=788, amount=2, data=0, tag=null}}
[09:50:10 WARN]: java.lang.ClassCastException: class com.viaversion.viaversion.api.minecraft.item.DataItem cannot be cast to class java.lang.Integer (com.viaversion.viaversion.api.minecraft.item.DataItem is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @23a49a0e; java.lang.Integer is in module java.base of loader 'bootstrap')
[09:50:10 WARN]:        at com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets.lambda$registerRewrites$2(EntityPackets.java:162)
[09:50:10 WARN]:        at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:126)
[09:50:10 WARN]:        at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:381)
[09:50:10 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[09:50:10 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[09:50:10 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390)[09:50:10 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:378)[09:50:10 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[09:50:10 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[09:50:10 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[09:50:10 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[09:50:10 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[09:50:10 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[09:50:10 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[09:50:10 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[09:50:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[09:50:10 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[09:50:10 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[09:50:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[09:50:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[09:50:10 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[09:50:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[09:50:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by masterblaster221** [comment]
Any help would be appreciated.

**Comment by WiIIiam278** [comment]
HuskHomes only works on Minecrafrt 1.16.5+ servers, I can't guarantee comparability nor can I provide support for your setup.

**Comment by masterblaster221** [comment]
I think I made a miss understanding of my problem my problem is with my 1.19.2 servers with via version. 1.12.2 is working on paper just not cross-server and I only want it to work on 1.19.2.  my servers on 1.12.2 are admin servers and not for cross-teleportation. I may be wrong but via version should still work when I'm on the 1.19.2 server and the 1.19.2 client 
viaverson is just a plugin so I should be able to teleport on the new version, such as 1.19.3 as 1.19.4 is not out yet. I'm only commenting again to clear up any confusion if there is so
