### ISSUE TITLE
fabric: Kick when reading plugin messages

### ISSUE THREAD

**Issue by masterblaster221** [WiIIiam278/HuskHomes2#367]
if more then 2 people are on the proxy then I get kicked from the fabric server.
here is my error 

java.lang.IllegalStateException: Cannot register channel 'indrev:update_modular_level'. Too many channels registered!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:2101) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3657) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:23:29 INFO]: endi0 lost connection: Invalid payload REGISTER!

**Comment by masterblaster221** [comment]
I updated the other version from last bug report.

**Comment by WiIIiam278** [comment]
This seems impossible to be a fabric issue -- the stacktrace contains references to org.bukkit classes (Spigot/Paper). Are you sure you're using fabric?

**Comment by masterblaster221** [comment]
Yep 100% Im running fabric here is the full log https://pastebin.com/w9h0gi91

**Comment by masterblaster221** [comment]
oh i gave the logs from the wrong server  the paste bin is the right one

**Comment by masterblaster221** [comment]
I gave the wrong log https://pastebin.com/w9h0gi91

**Comment by WiIIiam278** [comment]
Interesting, I'll take a look

**Comment by WiIIiam278** [comment]
@masterblaster221 Hi -- I've done some pretty thorough testing and I think I've fixed this now :)

https://modrinth.com/plugin/huskhomes/version/hIh47Fdr

Please try with the latest.
