### ISSUE TITLE
Inserting a new teleport to the database causes constraint exception as it does not delete the existing one first

### ISSUE THREAD

**Issue by thiagogebrimm** [WiIIiam278/HuskHomes2#414]
It appears that it needs to finish the teleport to and does not teleport the player

Also I identified an error in the console:
```
[14:06:11] [Server thread/INFO]: joaorodini issued server command: /huskhomes:warp arena
[14:06:11] [Craft Scheduler Thread - 1069 - HuskHomes/ERROR]: [HuskHomes] Failed to clear the current teleport of joaorodini
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'de02a70e-5697-350e-83f5-6200d73ce467' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-j-8.0.32.jar:8.0.32]
	at net.william278.huskhomes.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at net.william278.huskhomes.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at net.william278.huskhomes.database.MySqlDatabase.setCurrentTeleport(MySqlDatabase.java:645) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at net.william278.huskhomes.teleport.Teleport.lambda$execute$4(Teleport.java:162) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at net.william278.huskhomes.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:53) ~[HuskHomes-Plugin-4.3.3-b5100fa.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WiIIiam278** [comment]
Is this an offline mode server (cracked)?

**Comment by thiagogebrimm** [comment]
This error appeared once, what has happened is players who have delay to teleport end up crashing and cannot teleport and sends the error message that he needs to wait for another teleport to finish

**Comment by WiIIiam278** [comment]
This is a side effect of #415 &mdash; where the task isn't cancelled properly, causing a teleport to be already present when trying to insert another one.
