### ISSUE TITLE
[Folia]A server crash when /tpa or /back

### ISSUE THREAD

**Issue by starmc63** [WiIIiam278/HuskHomes2#424]
[19:33:36] [Region Scheduler Thread #4/INFO]: zyfdage issued server command: /back
[19:33:38] [Region Scheduler Thread #5/INFO]: JEPXWE issued server command: /tpa OkayPlanet39241
[19:33:48] [Region Scheduler Thread #4/INFO]: zyfdage issued server command: /back
[19:33:51] [Region Scheduler Thread #5/INFO]: JEPXWE issued server command: /tpa nanfeng_123
[19:33:53] [Region Scheduler Thread #4/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1675 centered at chunk [58, -202] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1698) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:489) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:860) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:598) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:739) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	... 6 more
[19:33:53] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[19:33:53] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[19:33:53] [Region shutdown thread/INFO]: Stopping server

**Comment by starmc63** [comment]
may be preload chunk can resolve it?

**Comment by WiIIiam278** [comment]
Seems like a folia issue. Report to folia.

**Comment by WiIIiam278** [comment]
Tracking on Folia.
