### ISSUE TITLE
/home ERROR with SQL

### ISSUE THREAD

**Issue by SnivyJ** [WiIIiam278/HuskHomes2#93]
[21:25:19] [Craft Scheduler Thread - 15/WARN]: [HuskHomes] An SQL exception occurred updating the player home cache
>java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:947) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:130) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:5913) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5581) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5610) ~[Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at me.william278.huskhomes2.data.DataManager.getPlayerHomes(DataManager.java:168) ~[?:?]
at me.william278.huskhomes2.commands.HomeCommand$Tab.lambda$updatePlayerHomeCache$0(HomeCommand.java:72) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) [Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [Spigot-1.17.1.jar:3238-Spigot-6c1c1b2-9217b52]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

When I update to 2.8.2 Some player use /home These appear in the CONSOLE And the player's tab completion cannot be used

**Comment by WiIIiam278** [comment]
@SnivyJ This can sometimes happen depending on your SQL version. You should be able to fix it by going into your config.yml and updating your params to append the `&zeroDateTimeBehavior=convertToNull` flag to your MySQL connection string
```yml
    params: '?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
```
