### ISSUE TITLE
Pl3xmap integration error

### ISSUE THREAD

**Issue by rlane85** [WiIIiam278/HuskHomes2#99]
Trying to integrate HuskHomes with Pl3xMap. Both are working fine independently. But when changed my config.yml to

```
map_integration:
  enabled: true
  plugin: pl3xmap
  markers:
    public_homes:
      show: true
      set_name: Public Homes
    warps:
      show: true
      set_name: Warps
```
And start the server, I get this error and HuskHomes shuts down with this stack trace in the console:
```

05.10 20:12:36 [Server] ERROR Error occurred while enabling HuskHomes v2.9 (Is it up to date?)
05.10 20:12:36 [Server] INFO java.lang.IllegalArgumentException: No image registered for key 'public_home'
05.10 20:12:36 [Server] INFO at net.pl3x.map.plugin.api.IconRegistry.noImageRegistered(IconRegistry.java:95) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
05.10 20:12:36 [Server] INFO at net.pl3x.map.plugin.api.IconRegistry.unregister(IconRegistry.java:52) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
05.10 20:12:36 [Server] INFO at me.william278.huskhomes2.integrations.map.Pl3xMap.initialize(Pl3xMap.java:103) ~[HuskHomes-2.9 (1).jar:?]
05.10 20:12:36 [Server] INFO at me.william278.huskhomes2.HuskHomes.onEnable(HuskHomes.java:219) ~[HuskHomes-2.9 (1).jar:?]
05.10 20:12:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-296]
05.10 20:12:36 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
05.10 20:12:36 [Server] INFO Disabling HuskHomes v2.9
05.10 20:12:36 [Server] INFO HuskHomesHikariPool - Shutdown initiated...
05.10 20:12:36 [Server] INFO HuskHomesHikariPool - Shutdown completed.
05.10 20:12:36 [Server] INFO Disabled HuskHomes version 2.9
```

**Comment by WiIIiam278** [comment]
@rlane Thanks for the spot, I've fixed it. If you're able to compile the latest commit, do so and it'll work, otherwise join the discord server, open a ticket and i'll hand you the new build. I'll wait a few days for any other issues with 2.9 before pushing this in with 2.9.1

**Comment by rlane85** [comment]
Thanks for the quick update! Will try it out tomorrow
